version: "3.9"

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=aryadisastra63@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml
      - ./traefik/acme.json:/letsencrypt/acme.json
      - ./traefik/dynamic_conf:/dynamic_conf
    networks:
      - web
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dtech_fe
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dtech.rule=Host(`d-tech.dev`) || Host(`www.d-tech.dev`)"
      - "traefik.http.routers.dtech.entrypoints=websecure"
      - "traefik.http.routers.dtech.tls.certresolver=letsencrypt"
      - "traefik.http.services.dtech.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.redirect-www.redirectregex.regex=^https://www\\.(.*)"
      - "traefik.http.middlewares.redirect-www.redirectregex.replacement=https://$1"
      - "traefik.http.middlewares.redirect-www.redirectregex.permanent=true"
      - "traefik.http.routers.dtech.middlewares=redirect-www"
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: false